### ISSUE TITLE
Support for macos-14 runner (ARM64)

### ISSUE THREAD

**Issue by zuckschwerdt** [melusina-org/setup-macports#1]
Would it be possible to add support for the `macos-14` runner? It is an interesting target because it runs on `arm64` (M1) arch.

Currently I get something like
```
curl: (3) URL rejected: Malformed input to a URL function
Error: Cannot download package ''
##[error]Process completed with exit code 1.
```

**Comment by foretspaisibles** [comment]
Thank you for your report and your interest in setup-macports! Yes it's certainly possible. It's done, see version 1.1.3. Please share your feedback and your other improvement ideas!

**Comment by zuckschwerdt** [comment]
Thank you for the instant support! Works flawlessly with `macos-14` now.

I recommend everyone to use this simple and elegant action in MacOS workflows to ensure building with MacPorts works as well as building with Homebrew.

I'll be adding it to all my projects, starting with SoapySDR, rtl_433.

I use it with e.g. (full example)
```
jobs:
  macos_macports_build_job:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-14]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: melusina-org/setup-macports@v1
      - name: Install ports
        run: sudo port install soapysdr libusb libiio libad9361-iio
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build
```

to check that everything builds nicely on Intel (`macos-12`) and ARM64 (`macos-14`).

One small note: when installing more involved ports (e.g. dbus, dep of libiio here) then `sudo` might still be needed on `port install` to properly setup some system startup items.
